eAcademy/Controllers/DashboardParentController.cs
using eAcademy.DataModel;
using eAcademy.HelperClass;
using eAcademy.Helpers;
using eAcademy.Models;
using eAcademy.Services;
using eAcademy.ViewModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eAcademy.Controllers
{
    [Parent_CheckSessionAttribute]
    public class DashboardParentController : Controller
    {
        //
        // GET: /ParentDashboard/

        public int ParentRegId;
        public string ParentUserName;
        public int StudentRegId;
        int DefaultStudentRegId;
        UserActivityHelper useractivity = new UserActivityHelper();
        protected override void OnActionExecuting(ActionExecutingContext ctx)
        {
            ParentRegId = Convert.ToInt32(Session["ParentRegId"]);
            ParentUserName = Convert.ToString(Session["ParentUserName"]);
            StudentRegId = Convert.ToInt32(Session["StudentRegId"]);
            DefaultStudentRegId = Convert.ToInt32(Session["DefaultStudentRegId"]);
        }
        public JsonResult getDate(int acid)
        {
            try
            {
                AcademicyearServices AcYear = new AcademicyearServices();
                var ans = AcYear.date(acid);
                string sdate = ans.StartDate.ToString("dd/MM/yyyy");
                string edate = ans.EndDate.ToString("dd/MM/yyyy");
                EventServices holidays = new EventServices();
                var HolidaysList = holidays.getHolidaysList(acid);
                return Json(new { sd = sdate, ed = edate, HolidaysList }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(e.Message, JsonRequestBehavior.AllowGet);
            }
        }
        public JsonResult FutureActiveDate()
        {
            AcademicyearServices AcYear = new AcademicyearServices();
            var CurrentAcYear = AcYear.getCurrentAcYear();
            string StartingEnableDate = DateTimeByZone.getCurrentDate().ToString("dd/MM/yyyy");
            string EndingEnableDate = DateTimeByZone.getCurrentDate().ToString("dd/MM/yyyy");
            for (int i = 0; i < CurrentAcYear.Count; i++)
            {
                DateTime CurrentDate = DateTimeByZone.getCurrentDate();
                DateTime sdate = CurrentAcYear[i].StartDate;
                DateTime edate = CurrentAcYear[i].EndDate;
                if (sdate <= CurrentDate && CurrentDate <= edate)
                {
                    EndingEnableDate = edate.ToString("dd/MM/yyyy");
                    EventServices holidays = new EventServices();
                    int acid = CurrentAcYear[i].AcademicYearId;
                    var HolidaysList = holidays.getHolidaysList(acid);
                    return Json(new { StartingEnableDate, EndingEnableDate, HolidaysList }, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(new { StartingEnableDate, EndingEnableDate }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult PastActiveDate()
        {
            AcademicyearServices AcYear = new AcademicyearServices();
            var CurrentAcYear = AcYear.getCurrentAcYear();
            string StartingEnableDate = DateTimeByZone.getCurrentDate().ToString("dd/MM/yyyy");
            string EndingEnableDate = DateTimeByZone.getCurrentDate().ToString("dd/MM/yyyy");
            for (int i = 0; i < CurrentAcYear.Count; i++)
            {
                DateTime CurrentDate = DateTimeByZone.getCurrentDate();
                DateTime sdate = CurrentAcYear[i].StartDate;
                DateTime edate = CurrentAcYear[i].EndDate;
                if (sdate <= CurrentDate && CurrentDate <= edate)
                {
                    StartingEnableDate = sdate.ToString("dd/MM/yyyy");
                    EventServices holidays = new EventServices();
                    int acid = CurrentAcYear[i].AcademicYearId;
                    var HolidaysList = holidays.getHolidaysList(acid);
                    return Json(new { StartingEnableDate, EndingEnableDate, HolidaysList }, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(new { StartingEnableDate, EndingEnableDate }, JsonRequestBehavior.AllowGet);
        }

        public JsonResult CurrentActiveDate()
        {
            AcademicyearServices AcYear = new AcademicyearServices();
            var CurrentAcYear = AcYear.getCurrentAcYear();
            string StartingEnableDate = DateTimeByZone.getCurrentDate().ToString("dd/MM/yyyy");
            string EndingEnableDate = DateTimeByZone.getCurrentDate().ToString("dd/MM/yyyy");

            for (int i = 0; i < CurrentAcYear.Count; i++)
            {
                DateTime CurrentDate = DateTimeByZone.getCurrentDate();
                DateTime sdate = CurrentAcYear[i].StartDate;
                DateTime edate = CurrentAcYear[i].EndDate;
                if (sdate <= CurrentDate && CurrentDate <= edate)
                {
                    EndingEnableDate = edate.ToString("dd/MM/yyyy");
                    StartingEnableDate = sdate.ToString("dd/MM/yyyy");
                    int acid = CurrentAcYear[i].AcademicYearId;
                    return Json(new { sd = StartingEnableDate, ed = EndingEnableDate }, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(new { sd = StartingEnableDate, ed = EndingEnableDate }, JsonRequestBehavior.AllowGet);
        }
        public JsonResult CustomeActiveDate(int acid)
        {
            AcademicyearServices AcYear = new AcademicyearServices();
            var ans = AcYear.date(acid);
            string StartingEnableDate = DateTimeByZone.getCurrentDate().ToString("dd/MM/yyyy");
            string EndingEnableDate = DateTimeByZone.getCurrentDate().ToString("dd/MM/yyyy");
            EventServices holidays = new EventServices();
            var HolidaysList = holidays.getHolidaysList(acid);
            DateTime CurrentDate = DateTimeByZone.getCurrentDate();
            DateTime sdate = ans.StartDate;
            DateTime edate = ans.EndDate;
            if (sdate <= CurrentDate && CurrentDate <= edate)
            {
                StartingEnableDate = sdate.ToString("dd/MM/yyyy");

                return Json(new { sd = StartingEnableDate, ed = EndingEnableDate, HolidaysList }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                StartingEnableDate = sdate.ToString("dd/MM/yyyy");
                EndingEnableDate = edate.ToString("dd/MM/yyyy");
                return Json(new { sd = StartingEnableDate, ed = EndingEnableDate, HolidaysList }, JsonRequestBehavior.AllowGet);
            }
        }

        public JsonResult totalstudent()
        {
            try
            {
                var serverTime = DateTimeByZone.getCurrentDateTimeDashboard();
                return Json(new { serverTime }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(new { ErrorMessage = e.Message.ToString() }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult Dashboard()
        {
            try
            {
                int yearId = 0; int classId = 0; int secId = 0;
                if (Session["PrimaryUser"] != "Guardian")
                {
                    AdmissionTransactionServices admissionTransaction = new AdmissionTransactionServices();
                    if (Session["ParentStudentList"] == null)
                    {
                        var StudentList = admissionTransaction.getStudentList(ParentRegId);
                        Session["ParentStudentList"] = StudentList;
                        var DefaultStudentName = admissionTransaction.getDefaultStudent(ParentRegId).FirstOrDefault().StudentName;
                        Session["DefaultStudentName"] = DefaultStudentName;
                        DefaultStudentRegId = admissionTransaction.getDefaultStudent(ParentRegId).FirstOrDefault().StudentRegisterId.Value;
                        AssignClassToStudentServices Assclas = new AssignClassToStudentServices();
                        var getRow = Assclas.getCurrentActiveClass(DefaultStudentRegId);
                        classId = getRow.ClassId.Value;
                        secId = getRow.SectionId.Value;
                        yearId = getRow.AcademicYearId.Value;
                        // get academicYear, class, section
                        //     AcademicyearServices AcYear = new AcademicyearServices();
                        ClassServices clas = new ClassServices();
                        SectionServices sec = new SectionServices();
                        // var getYear = AcYear.AcademicYear(year).AcademicYear1;
                        var getClass = clas.getClassNameByClassID(classId).ClassType;
                        var getSection = sec.getSectionName(classId, secId).SectionName;

                        Session["ParentStudentClass"] = getClass;
                        Session["DefaultStudentRegId"] = DefaultStudentRegId;
                        Session["StudentRegId"] = DefaultStudentRegId;
                    }
                }

                ViewBag.LastLogin = Session["LastLogin"];

                var currentDate = DateTimeByZone.getCurrentDate();

                AnnouncementServices announce = new AnnouncementServices();
                var announcementList = announce.getAnnouncementList(currentDate);
                ViewBag.count = announcementList.Count;

                // for Last Request

                ParentLeaveRequestServices leavReq = new ParentLeaveRequestServices();
                var LeaveRequestStatus1 = leavReq.getLeaveReqDetail(DefaultStudentRegId);
                if (LeaveRequestStatus1 != null)
                {
                    ViewBag.fdate = LeaveRequestStatus1.FromDate.Value.ToString("dd MMM, yyyy");

eAcademy/Controllers/aceConnect/DashboardController.cs
using eAcademy.ApiServices;
using eAcademy.ApiModels;
using eAcademy.DataModel;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web;
using System.Data.Objects.SqlClient;



namespace eAcademy.Controllers.aceConnect
{
    public class DashboardController : ApiController
    {
        EacademyEntities dc = new EacademyEntities();
        AnnouncementServices announcement = new AnnouncementServices();
        AdmissionTransactionServices Student = new AdmissionTransactionServices();

        public object Post(Token t)
        {
            string tokenId = t.token;
            TokenAuthSservices tok = new TokenAuthSservices();
            var checkValidUser = tok.IsValidUser(tokenId);
            if(checkValidUser != null)
            {
                int ParentRegId = checkValidUser.UserId.Value;
                var AnnouncementList = announcement.GetAnnouncementList();
                var StudentList = Student.GetStudentList(ParentRegId);
                string UserValidation = "Success";
                return new { AnnouncementList, StudentList, UserValidation };
            }
            else
            {
                string UserValidation = "Time expired. Login again";
                return new { UserValidation };
            }
        }




    }
}

eAcademy/Views/DashboardParent/StudentCredential.cshtml
@using eAcademy.Models;
@model IEnumerable<eAcademy.Models.GuardianStudentList>
@{
    ViewBag.Title = "StudentCredential";
    Layout = "~/Views/Shared/StudentAfterLogin.cshtml";
}
<style>
    .btn-radio {
        width: 100%;
    }

    .img-radio {
        opacity: 0.5;
        margin-bottom: 5px;
        height: 112px;
        width: 135px;
        margin-left: 1px;
    }

    .space-20 {
        margin-top: 20px;
    }

    .st_credential {
        margin-left: 0px;
        margin-right: 86px;
        width: 1310px;
    }

    .credential_form {
        margin-top: 51px;
        width: auto;
    }

    #btn_StudentCredential {
        margin-left: 167px;
    }
</style>

<section class="content" style="height:100%">
    <div class="row">
        <section class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="box box-solid bg-teal-gradient st_credential">
                <div class="box-header bg-gray">
                    <i class="fa fa-clipboard "></i>
                    <h3 class="box-title">@ResourceCache.Localize("StudentCredential")</h3>
                    <div class="box-tools pull-right">
                        <a class="" data-widget="collapse"><i class="fa fa-chevron-down"></i></a>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="col-md-6 col-md-offset-3">
                            @Html.Partial("~/Views/Shared/ViewMessgae.cshtml")
                            @Html.Partial("~/Views/Shared/ModelValidation.cshtml")
                            @Html.Partial("~/Views/Shared/MandatoryFieldErrorMessage_List.cshtml")
                            <form action="@Url.Action("StudentCredential", "DashboardParent")" method="post" enctype="multipart/form-data" class="form-horizontal well credential_form" role="form">
                                <div class="row">
                                    @foreach (var item in Model)
                                    {
                                        <div class="col-xs-4">
                                            <img src="~/Documents/StudentPhoto/@item.StudentPhoto" class="img-responsive img-radio">
                                            <button type="button" class="btn btn-primary btn-radio" id="@item.StudentRegId" value="@item.StudentRegId">@ResourceCache.Localize("Select_Student")</button>
                                            <input type="checkbox" id="left-item" class="hidden">
                                        </div>
                                    }
                                    <input type="hidden" id="sel_StudentRegId" class="current_button" name="sel_StudentRegId" value="@ViewBag.stuReg">
                                </div>
                                <div class="row space-20">
                                    <div class="col-xs-12">
                                        <div class="form-group">
                                            <label for="inputTitle" class="col-sm-4 control-label">@ResourceCache.Localize("StudentId")</label>
                                            <div class="col-sm-6">
                                                <input type="text" class="current_button col-lg-12" id="txt_StudentId" name="txt_StudentId" value="@ViewBag.StudentId">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="inputTitle" class="col-sm-4 control-label">@ResourceCache.Localize("DateofBirth")</label>
                                            <div class="col-sm-6">
                                                <input type="text" class="current_button col-lg-12" id="txt_dob" name="txt_dob" value="@ViewBag.DOB">
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <div class="col-sm-10">
                                                <input type="submit" id="btn_StudentCredential" name="btn_StudentCredential" class="btn btn-primary" value="@ResourceCache.Localize("Submit")" />
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
                <div class="box-footer clearfix no-border">
                </div>
            </div>
        </section>

    </div>
</section>


@section scriptsContainer{
    <script type="text/javascript">

        $(document).ready(function () {

            $(function () {
                $('.btn-radio').click(function (e) {
                    $('.btn-radio').not(this).removeClass('active')
                        .siblings('input').prop('checked', false)
                        .siblings('.img-radio').css('opacity', '0.5');
                    $(this).addClass('active')
                        .siblings('input').prop('checked', true)
                        .siblings('.img-radio').css('opacity', '1');
                });
            });

            var x;
            $(document).on('click', '.btn-radio', function () {
                x = $(this).attr('id');
                $("#sel_StudentRegId").val(x);
            });

            $("#btn_StudentCredential").click(function (event) {
                $("#divSuccess1").hide();
                $("#divSuccess2").hide();

                var studentId = $("#txt_StudentId").val();
                var dob = $("#txt_dob").val();
                var r = $("#sel_StudentRegId").val();
                alert(studentId);
                alert(dob);
                alert(r);

                var a = [];
                var field_val = [];
                $(".current_button").each(function () {
                    var valu = $(this).val();
                    if (valu == '') {
                        var null_id = $(this).attr('id');
                        if (null_id == 'sel_StudentRegId') {

                            a.push('@ResourceCache.Localize("PleaseSelectStudent")');
                        }
                        if (null_id == 'txt_StudentId') {

                            a.push('@ResourceCache.Localize("Please_enter_student_Id")');
                        }
                        if (null_id == 'txt_dob') {

                            a.push('@ResourceCache.Localize("Please_enter_date_of_birth")');
                        }
                    }
                    else {
                    }
                });

                if (a.length != 0) {
                    $("#MandatoryFieldErrorMessage_List").show();
                    $(".List_jErr").append().empty();
                    $.each(a, function (i, v) {
                        if (a[i] != "" && a[i] != null) {
                            li = $("<li></li>").text(a[i]);
                            $(".List_jErr").append(li);
                        }
                    });
                    a = [];
                    return false;
                }
                else {
                    $("#MandatoryFieldErrorMessage_List").hide();
                }

            });
        });
    </script>
}