eAcademy/Models/StudentRemark.cs
using System;
namespace eAcademy.Models
{
    public class StudentRemark
    {
        public string date { get; set; }
        public string CommentFrom { get; set; }
        public string Remark { get; set; }
        public string Name { get; set; }
        public DateTime? date1 { get; set; }
        public string Date { get; set; }
    }
}

eAcademy/Controllers/ModulesController.cs
using eAcademy.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using eAcademy.ViewModel;
using System.Net;
using eAcademy.Models;
using eAcademy.Helpers;
using eAcademy.HelperClass;

namespace eAcademy.Controllers
{
    [Student_Parent_SessionAttribute]
    public class ModulesController : Controller
    {
        //
        // GET: /Modules/

        StudentFacultyFeedback_service fb = new StudentFacultyFeedback_service();
        AssignClassToStudentServices clas = new AssignClassToStudentServices();
        AssignSubjectToSectionServices sub = new AssignSubjectToSectionServices();
        AssignFacultyToSubjectServices faculSub = new AssignFacultyToSubjectServices();
        HomeworkServices HW = new HomeworkServices();
        AssignmentServices Assgn = new AssignmentServices();
        SubjectnotesServices SubNote = new SubjectnotesServices();
        StudentfacultyquriesServices fQuery = new StudentfacultyquriesServices();
        

        public int StudentRegId;
        public int yearId;
        public int classId;
        public int secId;

        protected override void OnActionExecuting(ActionExecutingContext ctx)
        {
            StudentRegId = Convert.ToInt32(Session["StudentRegId"]);
            var getRow = clas.getAssigendClass(StudentRegId);
            if (getRow != null)
            {
                yearId = Convert.ToInt32(getRow.AcademicYearId);
                classId = Convert.ToInt32(getRow.ClassId);
                secId = Convert.ToInt32(getRow.SectionId);
                ViewBag.AllSubjects1 = sub.ShowSubjects(yearId, classId, secId);
            }
            AcademicyearServices AcYear = new AcademicyearServices();
            ViewBag.allAcademicYears = AcYear.ShowAcademicYears();
        }

        public ActionResult SubjectNotes()
        {
            return View();
        }

        public JsonResult NotesListResults(string sidx, string sord, int page, int rows, int? SM_AllSubjects, DateTime? SM_Notes_FromDate, DateTime? SM_Notes_ToDate)
        {
            int pageIndex = Convert.ToInt32(page) - 1;
            int pageSize = rows;
            IList<SubjectNotes> NotesList = new List<SubjectNotes>();
            if (SM_AllSubjects == 0 && SM_Notes_FromDate != null && SM_Notes_ToDate != null)
            {
                NotesList = SubNote.getStudentNotes(yearId, classId, secId, SM_Notes_FromDate.Value, SM_Notes_ToDate.Value);

            }
            if (SM_AllSubjects != 0 && SM_Notes_FromDate != null && SM_Notes_ToDate != null)
            {
                NotesList = SubNote.getStudentNotes(yearId, classId, secId, SM_AllSubjects.Value, SM_Notes_FromDate.Value, SM_Notes_ToDate.Value);
            }
            int totalRecords = NotesList.Count();
            var totalPages = (int)Math.Ceiling((float)totalRecords / (float)rows);
            if (sord != null)
            {
                if (sord.ToUpper() == "DESC")
                {
                    NotesList = NotesList.OrderByDescending(s => s.Subject).ToList();
                    NotesList = NotesList.Skip(pageIndex * pageSize).Take(pageSize).ToList();
                }
                else
                {
                    NotesList = NotesList.OrderBy(s => s.Subject).ToList();
                    NotesList = NotesList.Skip(pageIndex * pageSize).Take(pageSize).ToList();
                }
            }
            Session["JQGridList"] = NotesList;
            var jsonData = new
            {
                total = totalPages,
                page,
                records = totalRecords,
                rows = NotesList
            };

            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }

        public JsonResult CurrentActiveDate()
        {
            AcademicyearServices AcYear = new AcademicyearServices();
            var CurrentAcYear = AcYear.getCurrentAcYear();
            string StartingEnableDate = DateTimeByZone.getCurrentDate().ToString("dd/MM/yyyy");
            string EndingEnableDate = DateTimeByZone.getCurrentDate().ToString("dd/MM/yyyy");


            for (int i = 0; i < CurrentAcYear.Count; i++)
            {
                DateTime CurrentDate = DateTimeByZone.getCurrentDate();
                DateTime sdate = CurrentAcYear[i].StartDate;
                DateTime edate = CurrentAcYear[i].EndDate;
                if (sdate <= CurrentDate && CurrentDate <= edate)
                {
                    EndingEnableDate = edate.ToString("dd/MM/yyyy");
                    StartingEnableDate = sdate.ToString("dd/MM/yyyy");
                    int acid = CurrentAcYear[i].AcademicYearId;
                    return Json(new { sd = StartingEnableDate, ed = EndingEnableDate }, JsonRequestBehavior.AllowGet);
                }
            }
            return Json(new { sd = StartingEnableDate, ed = EndingEnableDate }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Notes_ExportToExcel()
        {
            try
            {
                List<SubjectNotes> NotesList = (List<SubjectNotes>)Session["JQGridList"];
                var list = NotesList.Select(o => new { Subject = o.Subject, NotesPosted_Date = o.NotesPosted_Date, Topic = o.Topic, Descriptions = o.Descriptions }).ToList();
                string fileName = ResourceCache.Localize("Notes_List");
                GenerateExcel.ExportExcel(list, fileName);
                return View("SubjectNotes");
            }
            catch (Exception ex)
            {
                ViewBag.error = ex.Message;
                return View("Error");
            }
        }

        public ActionResult Notes_ExportToPdf()
        {
            try
            {
                List<SubjectNotes> NotesList = (List<SubjectNotes>)Session["JQGridList"];
                string xfilePath = Server.MapPath("~/Views/") + "Sample1.pdf";
                string heading = ResourceCache.Localize("NotesList");
                GeneratePDF.ExportPDF_Portrait(NotesList, new string[] { "Subject", "NotesPosted_Date", "Topic", "Descriptions" }, xfilePath, heading);
                return File(xfilePath, "application/pdf", ResourceCache.Localize("NotesList.pdf"));
            }
            catch (Exception ex)
            {
                ViewBag.error = ex.Message;
                return View("Error");
            }
        }

        public void OpenSubjectNotesFile(string id)
        {
            try
            {
                int fid = Convert.ToInt32(QSCrypt.Decrypt(id));
                var getSubjectNotesFile = SubNote.getStudentNotesFile(fid).NotesFileName;
                string file = getSubjectNotesFile;
                if (file != "No file")
                {
                    string extention = System.IO.Path.GetExtension(file);
                    string FilePath = Server.MapPath("~/Documents/SubjectNotes/" + file);
                    WebClient User = new WebClient();
                    Byte[] FileBuffer = User.DownloadData(FilePath);
                    if (FileBuffer != null)
                    {
                        if (extention == ".pdf")
                        {
                            Response.ContentType = "application/pdf";
                        }
                        else if (extention == ".doc" || extention == ".docx")
                        {
                            Response.ContentType = "application/vnd.ms-word";
                        }
                        Response.AddHeader("content-length", FileBuffer.Length.ToString());
                        Response.BinaryWrite(FileBuffer);
                        Response.Flush();
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.error = ex.Message;
            }
        }

        public JsonResult getDate(int acid)
        {
            try
            {
                AcademicyearServices AcYear = new AcademicyearServices();
                var ans = AcYear.date(acid);
                string sdate = ans.StartDate.ToString("dd/MM/yyyy");
                string edate = ans.EndDate.ToString("dd/MM/yyyy");
                EventServices holidays = new EventServices();
                var HolidaysList = holidays.getHolidaysList(acid);
                return Json(new { sd = sdate, ed = edate, HolidaysList }, JsonRequestBehavior.AllowGet);
            }
            catch (Exception e)
            {
                return Json(e.Message, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult StudentRemark()
        {           
            List<SelectListItem> li = new List<SelectListItem>();
            li.Add(new SelectListItem { Text = ResourceCache.Localize("All") , Value = "All" });
            li.Add(new SelectListItem { Text = ResourceCache.Localize("ClassRemark"), Value = "ClassRemark" });
            li.Add(new SelectListItem { Text = ResourceCache.Localize("ProgressCardRemark"), Value = "ProgressCardRemark" });
            li.Add(new SelectListItem { Text = ResourceCache.Localize("ExamSubjectRemark"), Value = "ExamSubjectRemark" });
            li.Add(new SelectListItem { Text = ResourceCache.Localize("HomeworkRemark"), Value = "HomeworkRemark" });
            li.Add(new SelectListItem { Text = ResourceCache.Localize("AssignmentRemark"), Value = "AssignmentRemark" });
            li.Add(new SelectListItem { Text = ResourceCache.Localize("ELearningRemark"), Value = "ELearningRemark" });
            ViewBag.StatusList = li;           
            return View();
        }


        public JsonResult RemarkListResults(string sidx, string sord, int page, int rows, int Remark_allAcademicYears, string Status, DateTime? Remark_fdate, DateTime? Remark_toDate) 
        {
            int pageIndex = Convert.ToInt32(page) - 1;
            int pageSize = rows;
            StudentDailyAttendanceServices stuAttendance = new StudentDailyAttendanceServices();

eAcademy/Controllers/aceConnect/HomeworkController.cs
using eAcademy.ApiModels;
using eAcademy.ApiServices;
using eAcademy.HelperClass;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;

namespace eAcademy.Controllers.aceConnect
{
    public class HomeworkController : ApiController
    {
        AssignClassToStudentServices assignstudent = new AssignClassToStudentServices();
        int yearId;
        int classId;
        int secId;
        int studentRegId;

        public object Post(Homework h)
        {
            if (h.hwdate == null)
            {
                h.hwdate = DateTimeByZone.getCurrentDate();                
            }
            string tokenId = h.token;
            TokenAuthSservices tok = new TokenAuthSservices();
            var checkValidUser = tok.IsValidUser(tokenId);
            if (checkValidUser != null)
            {
                studentRegId = h.StudentRegId;
                var classDetail = assignstudent.GetClassDetails(studentRegId);
                yearId = classDetail.AcademicYearId.Value;
                classId = classDetail.ClassId.Value;
                secId = classDetail.SectionId.Value;
                HomeworkServices hw = new HomeworkServices();
                var List = hw.GetDateHomeworkList(yearId, classId, secId, h.hwdate.Value.Date);
                string UserValidation = "Success";
                return new { List, UserValidation };
            }
            else
            {
                string UserValidation = "Time expired. Login again";
                return new { UserValidation };
            }
        }
    }
}

eAcademy/Views/Modules/ModulesAssigned.cshtml
@model IEnumerable<eAcademy.ViewModel.StudentSubjectList>
@{
    ViewBag.Title = "ModulesAssigned";
    Layout = "~/Views/Shared/StudentAfterLogin.cshtml";
}

@Html.Partial("~/Views/Shared/NavbarHeader.cshtml")


<section class="maincontent-header">
    <div class="s_head col-lg-12">
        Modules Assigned
        <div class="row">
            <div class="col-lg-12 col-xs-12">
                <div class="btn-group btn-breadcrumb">
                    <a href="/DashboardStudent/Dashboard" class="btn btn-info"><i class="fa fa-dashboard"></i></a>
                    <a href="/Modules/SubjectNotes" class="btn btn-info">Modules</a>
                    <a href="/Modules/ModulesAssigned" class="btn btn-info">Modules Assigned</a>
                </div>
            </div>
        </div>
    </div>
</section>

<ul class="nav nav-tabs">
    <li><a href="~/Modules/SubjectNotes">Subject Notes</a></li>
    <li><a href="~/Modules/Homework">Homework</a></li>
    <li><a href="~/Modules/Assignment">Assignment</a></li>
    <li><a href="~/Modules/ModulesAssigned">Modules Assigned</a></li>
</ul>


<section class="content" style="height:100%">
    <div class="row">

        @Html.Partial("~/Views/Shared/TempMessage.cshtml")


        <section class="col-lg-12">
            <div id="div_student">
                <div class="box box-solid bg-teal-gradient ">
                    <div class="box-header bg-primary ">
                        <i class="fa fa-clipboard "></i>
                        <h3 class="box-title">Modules Assigned</h3>
                        <div class="box-tools pull-right">
                            <a class="" data-widget="collapse"><i class="fa fa-chevron-down"></i></a>
                        </div>

                    </div><!-- /.box-header -->
                    @Html.Partial("~/Views/Shared/Print.cshtml")
                    <div class="box-body" id="show">
                        <div id="tbl_scrol">
                            <table class="table table-bordered table-striped">
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Subject)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Faculty)
                                    </th>
                                    <th>
                                        Feedback
                                    </th>
                                    <th>
                                        Queries
                                    </th>
                                </tr>

                                @foreach (var item in Model)
                                {
                                <tr>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Subject)
                                    </td>
                                    <td>
                                        @Html.DisplayFor(modelItem => item.Faculty)
                                        @*@Html.ActionLink(@item.Faculty, "FacultyDetails", new { id = item.FacultyId })*@
                                    </td>
                                    <td>
                                        @Html.ActionLink("Click here to send a Feedback", "FacultyFeedback", new { id = item.FacultyId })
                                    </td>
                                    <td>
                                        @Html.ActionLink("Click here to send a Query", "StudentQueries", new { id = item.FacultyId })
                                    </td>

                                </tr>
                                }

                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        @if (ViewBag.FacultyId != null)
        {
            <section class="col-lg-12">
                <div id="div_student">
                    <div class="box box-solid bg-teal-gradient ">
                        <div class="box-header bg-primary ">
                            <i class="fa fa-clipboard "></i>
                            <h3 class="box-title">FeedBack</h3>
                            <div class="box-tools pull-right">
                                <a class="" data-widget="collapse"><i class="fa fa-chevron-down"></i></a>
                            </div>

                        </div><!-- /.box-header -->

                        <form action="@Url.Action("ModulesAssigned", "Modules")" method="post" enctype="multipart/form-data">
                            <div class="box-body border-radius-none">
                                @Html.Partial("~/Views/Shared/RequiredField.cshtml")


                                <div class="col-lg-6">

                                    <div>Feedback <span class="glyphicon glyphicon-asterisk"></span></div>
                                   
                                        <textarea id="txt_facultyFeedback" name="txt_facultyFeedback" class="col-lg-12" placeholder="Feedback" title="Feedback" required="required"></textarea>

                                    
                                </div>

                                <div class="col-lg-6">


                                    <div class="FacultyFeedback-message col-lg-12"> <label></label></div>
                                    <input type="hidden" value="@ViewBag.FacultyId" id="facultyId" name="facultyId" />
                                    <div class="col-md-12"> <button type="submit" class="btn btn-sm btn_submit " id="btnFacultyFeedback"><i class="fa fa-caret-right"></i> Submit</button></div>

                                </div>

                            </div>
                        </form>



                        <div class="box-footer clearfix no-border">
                        </div>
                    </div>
                </div>
            </section>
        }


        @if (ViewBag.QueryFacultyId != null)
        {
            <section class="col-lg-12">
                <div id="div_student">
                    <div class="box box-solid bg-teal-gradient ">
                        <div class="box-header bg-primary ">
                            <i class="fa fa-clipboard "></i>
                            <h3 class="box-title">Queries</h3>
                            <div class="box-tools pull-right">
                                <a class="" data-widget="collapse"><i class="fa fa-chevron-down"></i></a>
                            </div>

                        </div><!-- /.box-header -->

                        <form action="@Url.Action("StudentQueries", "Modules")" method="post" enctype="multipart/form-data">
                            <div class="box-body border-radius-none">
                                @Html.Partial("~/Views/Shared/RequiredField.cshtml")


                                <div class="col-lg-6">

                                    <div>Add Queries <span class="glyphicon glyphicon-asterisk"></span></div>
                                    
                                        <textarea id="txt_StudentQuery" name="txt_StudentQuery" class="col-lg-12" placeholder="Queries" title="Queries" required="required"></textarea>

                                   
                                </div>

                                <div class="col-lg-6">


                                    <div class="StudentQuery-message col-lg-12"> <label></label></div>
                                    <input type="hidden" value="@ViewBag.QueryFacultyId" id="facultyId" name="facultyId" />
                                    <div class="col-md-12"> <button type="submit" class="btn btn-sm btn_submit " id="btnStudentQuery"><i class="fa fa-caret-right"></i> Submit</button></div>

                                </div>

                            </div>
                        </form>



                        <div class="box-footer clearfix no-border">
                        </div>
                    </div>
                </div>
            </section>
        }

    </div>

</section>