eAcademy/Controllers/GuardianController.cs
using eAcademy.HelperClass;
using eAcademy.Helpers;
using eAcademy.Models;
using eAcademy.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eAcademy.Controllers
{
    [Guardian_CheckSessionAttribute]
    public class GuardianController : Controller
    {
        //
        // GET: /Guardian/

        public int ParentRegId;
        public string ParentUserName;
        public int StudentRegId;

        UserActivityHelper useractivity = new UserActivityHelper();

        protected override void OnActionExecuting(ActionExecutingContext ctx)
        {
            ParentRegId = Convert.ToInt32(Session["ParentRegId"]);
            ParentUserName = Convert.ToString(Session["ParentUserName"]);
            StudentRegId = Convert.ToInt32(Session["StudentRegId"]);
        }

        public ActionResult StudentCredential()
        {
            if (Session["GuardianStudentName"] != null)
            {
               return RedirectToAction("Dashboard", "DashboardParent");
            }
            AdmissionTransactionServices transaction = new AdmissionTransactionServices();
            var StudentList = transaction.GetStudentRegId(ParentRegId);
            int count = StudentList.ToList().Count;
            ViewBag.count = count;
            Session["Guardian_menu"] = "DontShow";
            return View(StudentList);
        }

        [HttpPost]
        public ActionResult StudentCredential(GuardianStudentList m)
        {
            try
            {
                ViewBag.stuReg = m.sel_StudentRegId;
                if (ModelState.IsValid)
                {
                    int StudentRegId = Convert.ToInt32(QSCrypt.Decrypt(m.sel_StudentRegId));
                    StudentServices stu = new StudentServices();
                    var checkValidStudent = stu.CheckGuardianStudent_Credential(StudentRegId, m.txt_StudentId, m.txt_dob);
                    if (checkValidStudent != null)
                    {
                        Session["StudentRegId"] = checkValidStudent.StudentRegisterId;
                        var fname = checkValidStudent.FirstName;
                        var lname = checkValidStudent.LastName;
                        Session["GuardianStudentName"] = fname + " " + lname;
                        StudentRegId = Convert.ToInt32(Session["StudentRegId"]);
                        AssignClassToStudentServices Assclas = new AssignClassToStudentServices();
                        var getRow = Assclas.getCurrentActiveClass(StudentRegId);
                        int classId = getRow.ClassId.Value;
                        int secId = getRow.SectionId.Value;
                        ClassServices clas = new ClassServices();
                        SectionServices sec = new SectionServices();
                        var getClass = clas.getClassNameByClassID(classId).ClassType;
                        var getSection = sec.getSectionName(classId, secId).SectionName;
                        Session["GuardianStudentClass"] = getClass + " " + getSection;
                        Session["Guardian_menu"] = "Show";
                        return RedirectToAction("Dashboard","DashboardParent");
                    }
                    else
                    {
                        ViewBag.StudentId = m.txt_StudentId;
                        ViewBag.DOB = m.txt_dob;
                        ViewBag.ErrorMessage = ResourceCache.Localize("InvalidStudentCredential");
                        AdmissionTransactionServices transaction = new AdmissionTransactionServices();
                        var StudentList = transaction.GetStudentRegId(ParentRegId);
                        int count = StudentList.ToList().Count;
                        ViewBag.count = count;
                        return View(StudentList);
                    }
                }
                else
                {
                    ViewBag.StudentId = m.StudentId;
                    if (m.DOB != null)
                    {
                        ViewBag.DOB = m.DOB.ToString("dd/MM/yyyy");
                    }
                    return View();
                }
            }
            catch (Exception ex)
            {
                ViewBag.error = ex.Message;
                return View("Error");
            }
        }


        public ActionResult ChangeStudent()
        {
            Session["StudentRegId"] = null;
            Session["GuardianStudentName"] = null;
            Session["Guardian_menu"] = "DontShow";
            return RedirectToAction("StudentCredential");
        }


    }
}

eAcademy/Views/Guardian/StudentCredential.cshtml
@model IEnumerable<eAcademy.Models.GuardianStudentList>
@using eAcademy.Models
@{
    ViewBag.Title = "StudentCredential";
    Layout = "~/Views/Shared/StudentAfterLogin.cshtml";
}
<style>
    .img-radio:hover {
        opacity: 1;
    }

    .img-radio {
        opacity: 0.5;
        margin-bottom: 13px;
        height: 170px;
        width: 170px;
        border: none;
        border-radius: 50%;
        background-color: transparent !important;
        box-shadow: 0px 5px 15px rgba(0, 0, 0, 0.5);
    }

    .box-title {
        color: #fff;
        letter-spacing: 2px;
        font-size: 29px !important;
    }

    .container-content {
        margin-left: -270px;
        background-color: transparent;
    }

    .credential_form {
        margin-top: 51px;
        margin-left: auto;
        margin-right: auto;
        padding: 10px;
        background-color: transparent;
        width: 411px;
        height: 600px;
    }

    .s_bar {
        display: none;
    }

    .control-label {
    }


    #menu-toggle {
        display: none;
    }

    .s1 {
        list-style-type: none;
        overflow: hidden;
        text-align: center;
    }

        .s1 .s2 {
            display: inline-block;
        }

    .s3 {
        width: 390px;
        margin: auto;
        margin-top: 42px;
    }

    .in {
        display: inline-block;
        color: white;
    }
</style>


<div class="cen1">
    <form action="@Url.Action("StudentCredential", "Guardian")" method="post" enctype="multipart/form-data" class="form-horizontal   credential_form" role="form">
        <div class=" " style="text-align:center"><h3 class="box-title">@ResourceCache.Localize("StudentCredential")</h3></div>
        <div class=" ">
            <div class="s1">
                @Html.Partial("~/Views/Shared/ViewMessgae.cshtml")
                @Html.Partial("~/Views/Shared/ModelValidation.cshtml")
                @Html.Partial("~/Views/Shared/MandatoryFieldErrorMessage_List.cshtml")
                @foreach (var item in Model)
                {
                    <div class="s2">
                        <img src="~/Documents/@item.StudentId/@item.StudentPhoto" class="img-responsive img-radio img-thumbnail" id="s"><br />
                        <button type="button" class="btn button-sc btn-radio" id="@item.StudentRegId" value="@item.StudentRegId">@ResourceCache.Localize("Select_Student")</button>
                        <input type="checkbox" id="left-item" class="hidden">
                    </div>
                }
            </div>
            <input type="hidden" id="sel_StudentRegId" class="current_button" name="sel_StudentRegId" value="@ViewBag.stuReg">
        </div>
        <div class="s3 ">
            <div class="col-xs-4">
                <label for="inputTitle" class="in">@ResourceCache.Localize("StudentId")</label>
            </div>
            <div class="col-xs-8">
                <input type="text" class="current_button" id="txt_StudentId" name="txt_StudentId" value="@ViewBag.StudentId">
            </div>
        </div>
        <div class="   ">
            <div class="col-xs-4">
                <label for="inputTitle" class="in ">@ResourceCache.Localize("DateOfBirth")</label>
            </div>
            <div class="col-xs-8">
                <input type="text" class="current_button" id="txt_dob" name="txt_dob" readonly value="@ViewBag.DOB">
            </div>
        </div>
        <div class="   ">
            <div class="col-sm-4"></div>
            <input type="submit" id="btn_StudentCredential" name="btn_StudentCredential" class="btn btn-success col-sm-4" value="@ResourceCache.Localize("Submit")" />
            <div class="col-sm-4"></div>
        </div>
    </form>
</div>

@section scriptsContainer{
    <script type="text/javascript">

        $(document).ready(function () {

            $(function () {
                $('.btn-radio').click(function (e) {
                    $('.btn-radio').not(this).removeClass('active')
                        .siblings('input').prop('checked', false)
                        .siblings('.img-radio').css('opacity', '0.5');
                    $(this).addClass('active')
                        .siblings('input').prop('checked', true)
                        .siblings('.img-radio').css('opacity', '1');
                });
            });


            var x;
            $(document).on('click', '.btn-radio', function () {
                x = $(this).attr('id');
                $("#sel_StudentRegId").val(x);
            });

            $("#btn_StudentCredential").click(function (event) {
                $("#divSuccess1").hide();
                $("#divSuccess2").hide();

                var studentId = $("#txt_StudentId").val();
                var dob = $("#txt_dob").val();
                var r = $("#sel_StudentRegId").val();

                var a = [];
                var field_val = [];
                $(".current_button").each(function () {
                    var valu = $(this).val();
                    //alert("valu" + valu)
                    if (valu == '') {
                        var null_id = $(this).attr('id');
                        if (null_id == 'sel_StudentRegId') {
                            a.push('@ResourceCache.Localize("PleaseSelectStudent")');
                        }
                        if (null_id == 'txt_StudentId') {

                            a.push('@ResourceCache.Localize("Please_enter_student_Id")');
                        }
                        if (null_id == 'txt_dob') {

                            a.push('@ResourceCache.Localize("Please_enter_date_of_birth")');
                        }
                    }
                    else {
                    }
                });

                if (a.length != 0) {
                    $("#MandatoryFieldErrorMessage_List").show();
                    $(".List_jErr").append().empty();
                    $.each(a, function (i, v) {
                        if (a[i] != "" && a[i] != null) {
                            li = $("<li></li>").text(a[i]);
                            $(".List_jErr").append(li);
                        }
                    });
                    a = [];
                    return false;
                }
                else {
                    $("#MandatoryFieldErrorMessage_List").hide();
                }

            });
            $("#txt_dob").datepicker({
                changeMonth: true,
                changeYear: true,
                dateFormat: 'dd/mm/yy',
                maxDate: new Date
            });
        });
    </script>
}